//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _08.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHINHANH
    {
        public int STT { get; set; }
        public string MaDT { get; set; }
        public string TP { get; set; }
        public string Quan { get; set; }
        public string DiaChiCuThe { get; set; }
        public string SDT { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
    
        public virtual DOITAC DOITAC { get; set; }
    }
}
