//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _08.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDONDATHANG
    {
        public string MaDH { get; set; }
        public string MaTP { get; set; }
        public string MaDT { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string DanhGia { get; set; }
    
        public virtual DONDATHANG DONDATHANG { get; set; }
        public virtual THUCPHAM THUCPHAM { get; set; }
    }
}
