//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _08.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOPDONG
    {
        public string MaHD { get; set; }
        public string NgDaiDien { get; set; }
        public Nullable<short> SLChiNhanh { get; set; }
        public string SoTaiKhoan { get; set; }
        public string NganHang { get; set; }
        public string CNNganHang { get; set; }
        public string MaSoThue { get; set; }
        public Nullable<System.DateTime> NgayKy { get; set; }
        public string ThoiHan { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public string MaDT { get; set; }
        public string MaNV { get; set; }
    
        public virtual DOITAC DOITAC { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
